### ISSUE TITLE
相关配置问题

### ISSUE THREAD

**Issue by YoungBreath** [Traffic-Alpha/LLM-Assisted-Light#2]
请问有相关的环境，例如pytorch、cuda版本，或requirement.txt 说明文件吗

**Comment by wmn7** [comment]
你好，

非常感谢你对我们工作的关注。这个项目的环境配置非常简单，他是基于 [TransSimHub](https://github.com/Traffic-Alpha/TransSimHub) 环境的，你首先需要将 TransSimHub 安装完毕。

```
git clone https://github.com/Traffic-Alpha/TransSimHub.git
cd TransSimHub
pip install -e ".[rl]"
```

这个项目用到了 `langchain`，你需要额外进行安装。因为是直接调用的 OpenAI GPT4，所以没有用到训练（也就是 cuda 不需要）。后续应该会更新 requirement.txt 文件（因为最近工作重心在另外一个项目上，这个仓库可能会更新的慢一些）。

祝好，
