### ISSUE TITLE
Missing config file

### ISSUE THREAD

**Issue by BGGiser** [Traffic-Alpha/LLM-Assisted-Light#4]
Missing config file in 'utils' folder, program does not run properly

**Comment by wmn7** [comment]
Hello,

The format of config is as follows:

```
OPENAI_API_BASE: "https://api.openai.com/v1"
OPENAI_PROXY: xxx
OPENAI_API_KEY: xxx
OPENAI_API_MODEL: "gpt-4-1106-preview" # gpt-4, gpt-3.5-turbo-16k
```

Since it contains `OPENAI_API_KEY`, we did not upload it. You can write it according to the above format.
